### ISSUE TITLE
Data Generation

### ISSUE THREAD

**Issue by Bonbonwjj** [jsappl/DeepPreconditioning#2]
How can I get the generated data without the process of openfoam？ It's really complex to compile it with openfoam.

**Comment by jsappl** [comment]
Hey @Bonbonwjj sorry for the very late reply, I've seen your issue just now.

You can either generate our data set on your machine. Run the `wmake` command inside the `foam/newInterFoam/` folder to compile the custom OpenFOAM solver. Then `cd` into `preconditioner/` and run `python3 gen_data.py` to generate the data set of all the Laplacian matrices and corresponding solutions to the linear systems.

You can also provide your own data set of sparse symmetric positive matrices in `.npz` format by changing the `DATA_ROOT` argument in the `config.py` file to the appropriate folder.

As an example I have uploaded the `preconditioner/data/example_laplacian.npz` file for you.

Let me know if you need further help.

**Comment by jsappl** [comment]
We intend to switch to [`phiflow`](https://github.com/tum-pbs/PhiFlow) -> Closed

**Comment by Bonbonwjj** [comment]
Sorry for not seeing the message until now, since this repository hasn't been updated for a long time, I didn't think I'd get a reply. The problem has been solved, thank you very much. This repository is really helpful for my research. :)
